# Generated by Django 3.2.3 on 2021-07-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0002_auto_20210701_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.CharField(choices=[('0', 'INACTIVA'), ('1', 'ACTIVA')], default='1', max_length=1),
        ),
    ]
